server:  
  port: ${PORT:8763}
  servlet:
    session:
      timeout: 600

spring:
  application:
    name: scot-web
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: spring:session

  redis:
    host: 127.0.0.1
    port: 6039
    database: 2
    password: biggbang

logging:
  pattern:
    console: '%d{yyMMdd HH:mm:ssSSS} %8.8thread %1.-1level %25.25logger{50}#%4.4line %msg%n'
  level:
    com.rockbb: DEBUG

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
